/* Autogenerated by png2wx.pl on Mon May 23 13:54:18 2011 */
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif

#include <wx/filename.h>
#include <wx/mstream.h>
#include "ocpn_plugin.h"
#include "icons.h"

wxString _svg_deeprey_play;
wxString _svg_deeprey_toggled;
wxString _svg_deeprey_rollover;

void initialize_images(void)
{
#ifdef DEEPREY_USE_SVG
    wxFileName fn;
    wxString tmp_path;
    tmp_path = GetPluginDataDir("deeprey_pi");
    fn.SetPath(tmp_path);
    fn.AppendDir(_T("data"));

    fn.SetFullName(_T("deeprey_play.svg"));
    _svg_deeprey_play = fn.GetFullPath();

    fn.SetFullName(_T("deeprey_play_rollover.svg"));
    _svg_deeprey_rollover = fn.GetFullPath();

    fn.SetFullName(_T("deeprey_play_toggled.svg"));
    _svg_deeprey_rollover = fn.GetFullPath();

#endif
// VDR_USE_SVG
    return;
}
